Verifica valores únicos sem `NA` em chaves compostas
splor-mg/checks-planejamento pull request #54
Opened 2024-08-26 21:27 UTC by hslinhares

#closes https://github.com/splor-mg/dados-sigplan-planejamento/issues/49#issuecomment-2310154094

2024-08-27 15:36 UTC, fjuniorr commented on R/check_primary_key.R
> +check_primary_key <- function(
Acho melhor uma função genérica `check_composite_primary_key`.

2024-08-27 15:38 UTC, fjuniorr commented on R/check_primary_key.R
> +check_is_na <- function(
Pode criar outras funções pra deixar a implementação mais clara, mas a função `check_composite_primary_key` tem que garantir que não existem valores missing nem valores duplicados nas colunas que fazem parte da chave primária composta.

2024-08-27 15:44 UTC, fjuniorr commented on R/check_primary_key.R
> +    !is.na(uo_acao_cod)
Se eu entendi bem a função `is_complete` não faz o que a gente precisa. A documentação:

> Here, the first rule checks for missing data in the id variable, the second rule checks whether subrecords with id and turnover are complete, and the third rule checks whether subrecords with id, turnover and profit are complete.

parece indicar que se uma linha possuir as colunas passadas como argumento (eg. `id`, `turnover`), mas ela pode não possuir, as demais colunas são verificadas por missing values.

Vale um snippet pra confirmar o comportamento. Uma sugestão é usar os erros da [base](https://github.com/splor-mg/dados-sigplan-planejamento-2024/tree/a950492b20bd810485fcc92e22570386d268e11e) que originou o issue.

2024-08-28 15:03 UTC, hslinhares commented on R/check_primary_key.R
> +    !is.na(uo_acao_cod)
> Se eu entendi bem a função `is_complete` não faz o que a gente precisa. A documentação:
> 
> > Here, the first rule checks for missing data in the id variable, the second rule checks whether subrecords with id and turnover are complete, and the third rule checks whether subrecords with id, turnover and profit are complete.
> 
> parece indicar que se uma linha possuir as colunas passadas como argumento (eg. `id`, `turnover`), mas ela pode não possuir, as demais colunas são verificadas por missing values.
> 
> Vale um snippet pra confirmar o comportamento. Uma sugestão é usar os erros da [base](https://github.com/splor-mg/dados-sigplan-planejamento-2024/tree/a950492b20bd810485fcc92e22570386d268e11e) que originou o issue.

Eu devo testar incluir na função `is_complete` uma coluna não existente na base `programas_planejamento` ? Existente por exemplo somente em `acoes_planejamento`?

2024-08-28 15:43 UTC, hslinhares commented on R/check_primary_key.R
> +    !is.na(uo_acao_cod)
Adicionando parâmentros da primary-key da base `acoes_planejamento` para testar a base `programas_planejamento` retorna erro:
```R
rule<- validate::validator(is_complete(uo_programa_cod, programa_cod, is_deleted_programa, objetivo_estrategico_cod, diretriz_estrategica_cod, ods_titulo, uo_acao_cod, acao_cod, is_deleted_acao))
```
![image](https://github.com/user-attachments/assets/998f8b09-704e-419e-bdbc-78732b8174ca)

2024-08-29 14:48 UTC, hslinhares reviewed
@fjuniorr consegui construir uma versão funcional da função em 1be44ff4022e642ef02838ae7bd4b7b7e072cfef

2024-08-29 14:54 UTC, hslinhares commented on R/check_composite_primary_key.R
> +    pattern = c('uo_programa_cod|programa_cod|is_deleted_programa|objetivo_estrategico_cod|diretriz_estrategica_cod|ods_titulo') # Buscar essa informação do raw.schema primary-key? Parsear o nome da
@fjuniorr consigo buscar essa informação do raw.schema? faz mais sentido ler o arquivo `.yaml` em vez do `.json`? A função read_datapackage lê arquivos `yaml` ?

2024-08-29 15:16 UTC, hslinhares commented on R/check_composite_primary_key.R
> +  is_unique(df[cols])
Porque funciona com `df[cols]` e não funciona parseando `cols`

2024-08-29 15:22 UTC, hslinhares commented on R/check_composite_primary_key.R
> +  is_unique(df[cols])
Snipet de teste da função.
```R
sigplan <- read_datapackage('https://raw.githubusercontent.com/splor-mg/dados-sigplan-planejamento-2024/a950492b20bd810485fcc92e22570386d268e11e/datapackage.json'

programas_planejamento <- sigplan$programas_planejamento

check_composite_primary_key(programas_planejamento)

# resultado
 
Rules confronted: 2
   With fails   : 1
   With missings: 0
   Threw warning: 0
   Threw error  : 0
Browse[1]> violating(df, report)[,.(uo_programa_cod, programa_cod, is_deleted_programa, objetivo_estrategico_cod, diretriz_estrategica_cod, ods_titulo)]
    uo_programa_cod programa_cod is_deleted_programa objetivo_estrategico_cod diretriz_estrategica_cod                                   ods_titulo
              <num>        <num>              <lgcl>                    <num>                   <char>                                       <char>
 1:            1081           44               FALSE                       10                     <NA>    16 - Paz, Justiça e Instituições Eficazes
 2:            1081           44               FALSE                       NA                     <NA>    16 - Paz, Justiça e Instituições Eficazes
 3:            1481          148               FALSE                        7                     <NA>                   1 - Erradicação da Pobreza
 4:            1481          148               FALSE                        7                     <NA>               10 - Redução das Desigualdades
 5:            1481          148               FALSE                        7                     <NA> 8 - Trabalho Decente e Crescimento Econômico
 6:            1481          148               FALSE                       10                     <NA>                   1 - Erradicação da Pobreza
 7:            1481          148               FALSE                       10                     <NA>               10 - Redução das Desigualdades
 8:            1481          148               FALSE                       10                     <NA> 8 - Trabalho Decente e Crescimento Econômico
 9:            1481          148               FALSE                       11                     <NA>                   1 - Erradicação da Pobreza
10:            1481          148               FALSE                       11                     <NA>               10 - Redução das Desigualdades
11:            1481          148               FALSE                       11                     <NA> 8 - Trabalho Decente e Crescimento Econômico
12:            1261          172               FALSE                        1                     <NA>    16 - Paz, Justiça e Instituições Eficazes
13:            1261          172               FALSE                        3                     <NA>    16 - Paz, Justiça e Instituições Eficazes
14:            1261          172               FALSE                        6                     <NA>    16 - Paz, Justiça e Instituições Eficazes
15:            1261          172               FALSE                       11                     <NA>    16 - Paz, Justiça e Instituições Eficazes
```

2024-09-02 10:41 UTC, fjuniorr commented on R/check_primary_key.R
> +    !is.na(uo_acao_cod)
Criei um exemplo mais simples e eu estava errado na interpretação da documentação. Eu tinha achado que o snippet abaixo não ia gerar erros:

```python
library(validate)

acao <- data.frame(UO = c(1501, 1501), 
                   ACAO = c(4007, NA), 
                   OBJETIVO= c("foo", "bar"))
v <- validator(is_complete(UO, ACAO))

violating(acao, confront(acao, v))
```

mas ele corretamente indica que a linha 2 é problemática:

```
    UO ACAO OBJETIVO
2 1501   NA      bar
```

2024-09-02 11:09 UTC, fjuniorr requested changes
@hslinhares além das duas alterações no código vou pedir pra você já deixar a mensagem preparada.

Nesse caso a gente não sabe as colunas que vão estar disponíveis, o que complica bastante nosso trabalho. Uma alternativa é depois de receber os argumentos `df` e `columns` criar uma nova coluna `pkey` que é a concatenação de todas as colunas que fazem parte da chave primária. Dessa forma no momento de escrever a mensagem você sabe que a coluna `pkey` sempre vai estar disponível.

2024-09-03 09:47 UTC, fjuniorr commented
@hslinhares tentei mas não consegui descobrir o que está acontecendo na execução no modo interativo vs dentro da função.

Esse uso que você descobriu não está documentado, porque os argumentos da função deveriam ser:

```
When used in a validation rule: a bare (unquoted) list of variable names. When used directly, a comma-separated list of vectors of equal length.
```

Então acho que a gente pode assumir que isso não é possível e criar funções dedicadas para cada base (eg. `check_composite_primary_key_acoes`).

2024-09-03 12:20 UTC, hslinhares commented
> @hslinhares tentei mas não consegui descobrir o que está acontecendo na execução no modo interativo vs dentro da função.
> 
> Esse uso que você descobriu não está documentado, porque os argumentos da função deveriam ser:
> 
> ```
> When used in a validation rule: a bare (unquoted) list of variable names. When used directly, a comma-separated list of vectors of equal length.
> ```
> 
> Então acho que a gente pode assumir que isso não é possível e criar funções dedicadas para cada base (eg. `check_composite_primary_key_acoes`).

Consegui ler a mensagem de erro e o problema não é no formato da variável `col` como estavamos achando. Mas sim pq a variável `col` não está sendo encontrada, quando ela é definida dentro da função. Se definimos ela no ambiente global, como abaixo, a função funciona. Alguma sugestão pra consertar isso?


```R
sigplan = read_datapackage('https://raw.githubusercontent.com/splor-mg/dados-sigplan-planejamento-2024/a950492b20bd810485fcc92e22570386d268e11e/datapackage.json')
programas <- sigplan$programas_planejamento

df <- programas
cols <- names(programas)

check <- function(
  df
){
    rules <- validate::validator(
    is_complete(df[cols])
  )

    report <- validate::confront(df, rules)
    return(report)
}

check(programas)

# output
Rules confronted: 1
   With fails   : 1
   With missings: 0
   Threw warning: 0
   Threw error  : 0
```

2024-09-03 18:10 UTC, hslinhares commented
> Depender de uma variável global que tenha o mesmo nome e conteúdo da variável usada dentro da função é frágil.
> 
> Melhor a gente ir pra linha de criar funções dedicadas e usar os nomes fixos das colunas que compõem a chave primária.

@fjuniorr o que acha do código em formato parecido com este? Testei e os resultados foram corretos.

```R
test <- function(base, col){
if(col == 'programas'){
    df <- sigplan$programas_planejamento
    rule <- validate::validator(
      is_complete(uo_programa_cod, programa_cod, is_deleted_programa, objetivo_estrategico_cod, diretriz_estrategica_cod, ods_titulo), 
      is_unique(uo_programa_cod, programa_cod, is_deleted_programa, objetivo_estrategico_cod, diretriz_estrategica_cod, ods_titulo)
    )
   
  } else if (col == 'acoes'){
    df <- sigplan$acoes_planejamento
    rule <- validate::validator(
      is_complete(uo_acao_cod, acao_cod, is_deleted_acao),
      is_unique(uo_acao_cod, acao_cod, is_deleted_acao)
    )
  
  }else if (col == 'localizadores'){
    df <- sigplan$localizadores_todos_planejamento
    rule <- validate::validator(
      is_complete(uo_acao_cod, acao_cod, is_deleted_acao, localizador_cod),
      is_unique(uo_acao_cod, acao_cod, is_deleted_acao, localizador_cod)
    )
  
  }else if (col == 'indicadores'){
    df <- sigplan$indicadores_planejamento
    rule <- validate::validator(
      is_complete(programa_cod, is_deleted_programa, indicador, is_deleted_indicador),
      is_unique(programa_cod, is_deleted_programa, indicador, is_deleted_indicador)
    )
  }
report <- validate::confront(df, rule)
return(report) 
 }


test(sigplan, 'programas')
# output
Rules confronted: 2
   With fails   : 1
   With missings: 0
   Threw warning: 0
   Threw error  : 0

test(sigplan, 'acoes')
# output 
Rules confronted: 2
   With fails   : 0
   With missings: 0
   Threw warning: 0
   Threw error  : 0
test(sigplan, 'localizadores')

# output

Rules confronted: 2
   With fails   : 0
   With missings: 0
   Threw warning: 0
   Threw error  : 0

test(sigplan, 'indicadores')
# output
Rules confronted: 2
   With fails   : 0
   With missings: 0
   Threw warning: 0
   Threw error  : 0
```

2024-09-05 12:51 UTC, hslinhares reviewed
Função refatorada. Trabalhando agora na construção da mensagem a partir do violations_list

2024-09-05 14:12 UTC, hslinhares reviewed
Mensagem padrão incluída na função

2024-09-20 19:31 UTC, merged